[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "^1.0.1"

[[constraint]]
  name = "github.com/lucsky/cuid"
  version = "1.0.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.87"

[[constraint]]
  name = "github.com/jackc/pgx"
  version = "v3.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
