service: iotv-api

custom:
  stage: ${opt:stage}
environment:


provider:
  name: aws
  role: "${ssm:/services/iotv-api/${opt:stage}/LAMBDA_ROLE_ARN}"
  runtime: go1.x
  versionFunctions: false


package:
  individually: true


layers:
  ffmpeg:
    path: bin/layers/ffmpeg
    package:
      include:
        - bin/layers/ffmpeg/ffmpeg

  ffprobe:
    path: bin/layers/ffprobe
    package:
      include:
        - bin/layers/ffprobe/ffprobe

functions:
  graphql:
    awsKmsKeyArn: "${ssm:/services/iotv-api/${opt:stage}/LAMBDA_KMS_ARN}"
    handler: bin/graphql
    environment:
      EMAIL_AUTHENTICATIONS_TABLE: "${ssm:/services/iotv-api/${opt:stage}/EMAIL_AUTHENTICATIONS_TABLE}"
      JWT_SECRET: "${ssm:/services/iotv-api/${opt:stage}/JWT_SECRET~true}"
      SOURCE_VIDEOS_TABLE: "${ssm:/services/iotv-api/${opt:stage}/SOURCE_VIDEOS_TABLE}"
      USERS_TABLE: "${ssm:/services/iotv-api/${opt:stage}/USERS_TABLE}"
    events:
      - http:
          path: /graphql
          method: post
          cors: true
    package:
      exclude:
        - ./**
      include:
        - bin/graphql

  onVideoTranscodingComplete:
    awsKmsKeyArn: "${ssm:/services/iotv-api/${opt:stage}/LAMBDA_KMS_ARN}"
    handler: bin/on_video_transcoding_complete
    events:
      - sns:
          arn: "${ssm:/services/iotv-api/${opt:stage}/VIDEO_ENCODER_COMPLETE_ARN}"
    package:
      exclude:
        - ./**
      include:
        - bin/on_video_transcoding_complete

  #  onVideoTranscodingError:
  #    handler: bin/on_video_transcoding_error
  #    events:
  #      - sns:
  #          arn: ${self:custom.snsTopics.onVideoTranscodingError.${opt:stage, self:provider.stage}}
  #    package:
  #      include:
  #        - bin/on_video_transcoding_error
  #  onVideoTranscodingProgressing:
  #    handler: bin/on_video_transcoding_progressing
  #    events:
  #      - sns:
  #          arn: ${self:custom.snsTopics.onVideoTranscodingProgressing.${opt:stage, self:provider.stage}}
  #    package:
  #      include:
  #        - bin/on_video_transcoding_progressing
  #  onVideoTranscodingWarning:
  #    handler: bin/on_video_transcoding_warning
  #    events:
  #      - sns:
  #          arn: ${self:custom.snsTopics.onVideoTranscodingWarning.${opt:stage, self:provider.stage}}
  #    package:
  #      include:
  #        - bin/on_video_transcoding_warning

  onVideoUploadComplete:
    awsKmsKeyArn: "${ssm:/services/iotv-api/${opt:stage}/LAMBDA_KMS_ARN}"
    handler: bin/on_video_upload_complete
    environment:
      WIDESCREEN_FHD_PRESET_ID: "${ssm:/services/iotv-api/${opt:stage}/WIDESCREEN_FHD_PRESET_ID}"
    events:
      - sns:
          arn: "${ssm:/services/iotv-api/${opt:stage}/SOURCE_VIDEO_UPLOADED_ARN}"
    package:
      exclude:
        - ./**
      include:
        - bin/on_video_upload_complete
